import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/pages/Home.module.scss'

import { ImTruck } from "react-icons/im";


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Truck Tracker | Accueil </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.title}>
          <ImTruck/>
          <h1>Welcome on Truck Tracker </h1>
        </div>
        <div className={styles.citation}>
          <p>&rdquo;Fait gaffe a ton essence maggle&rdquo;</p>
          <p className={styles.name}>Cyril Q.</p>
        </div>
      
    </div>
  )
}

export default Home
